require: rubocop-rails
AllCops:
  NewCops: enable
  Include:
    - 'app/**/*.rb'
    - 'spec/**/*.rb'
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false