version: "3.3"
services:
  db:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - public
    volumes:
      - postgres_volume:/var/lib/postgresql/data:cached
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/dns_map
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - public
volumes:
  bundle_cache:
  postgres_volume:
networks:
  public:
    driver: bridge